version: "3.7"
services:
  db:
    image: postgres:14.4
    container_name: bloodbankmvc
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      POSTGRES_DB: bloodBankdb
      POSTGRES_USER: db_app
      POSTGRES_PASSWORD: db_app


#  bloodbank:
#    build: .
#    restart: always
#    ports:
#      - "8080:8080"
#    depends_on:
#       - db

